app:
    resource: "@AppBundle/Controller/"
    type:     annotation
homepage:
  path: /
  defaults: { _controller: AppBundle:Default:index }
login_page:
  path: /login
  defaults: { _controller: AppBundle:Default:loginPage }
signup_page:
  path: /signup
  defaults: { _controller: AppBundle:Default:signupPage }
login:
  path: /do_login
  defaults: { _controller: AppBundle:Default:login }
signup:
  path: /do_signup
  defaults: { _controller: AppBundle:Default:signup }
logout:
  path: /logout
  defaults: { _controller: AppBundle:Default:logout }
add_file:
  path: /add_file
  defaults: { _controller: AppBundle:Default:addFile }
check_user_permission:
  path: /check_user_permission
  defaults: { _controller: AppBundle:Default:checkUserPermission }